const String apiBaseUrl = "https://www.orderitto.com/";
const String apiLoginUrl = apiBaseUrl + "api/login";
const String apiProductsUrl = apiBaseUrl + "api/products";
const String apiAdsUrl = apiBaseUrl + "api/ads";
const String apiOrdesrUrl = apiBaseUrl + "api/orders?customer_id=";
const String apiSignupUrl = apiBaseUrl + "api/register";
const String apiUserInfoUrl = apiBaseUrl + "api/user";
const String apiShowCountryUrl = apiBaseUrl + "api/locations";
const String apiCategoriesListUrl = apiBaseUrl + "api/categories";
const String apiEditProfileUrl = apiBaseUrl + "api/profile";
const String apiCreateOrderUrl = apiBaseUrl + "api/orders";
const String apiOrderStatusUrl = apiBaseUrl + "api/orders/";
const String apiCartUrl = apiBaseUrl + "api/cart";
const String apiWishListUrl = apiBaseUrl + "api/wishlist";
const String apiStoresListUrl = apiBaseUrl + "api/stores";
const String apiSubCategoriesUrl = apiBaseUrl + "api/subCategories";
const String apiHomeProducts = apiBaseUrl + "api/homeProducts";
