const String apiMockImage =
    "https://cdn.pixabay.com/photo/2021/06/27/14/32/raspberry-6368999_1280.png";
const String apiBaseUrl = "https://www.cezma.com/";
const String apiLoginUrl = apiBaseUrl + "api/login";
const String apiProductsUrl = apiBaseUrl + "api/products";
const String apiOrdesrUrl = apiBaseUrl + "api/orders?customer_id=";
const String apiSignupUrl = apiBaseUrl + "api/register";
const String apiUserActivation = apiBaseUrl + "api/email/verify";
const String apiUserInfoUrl = apiBaseUrl + "api/profile";
const String apiShowCountryUrl = apiBaseUrl + "api/locations";
const String apiCategoriesListUrl = apiBaseUrl + "api/categories";
const String apiEditProfileUrl = apiBaseUrl + "api/profile";
const String apiCreateOrderUrl = apiBaseUrl + "api/orders";
const String apiOrderStatusUrl = apiBaseUrl + "api/orders/";
const String apiCartUrl = apiBaseUrl + "api/cart";
const String apiWishListUrl = apiBaseUrl + "api/wishlist";
const String apiStoresListUrl = apiBaseUrl + "api/stores";
const String apiSubCategoriesUrl = apiBaseUrl + "api/subCategories";
const String apiHomeUrl = apiBaseUrl + "api/home";
const String apiCountries = apiBaseUrl + "api/locations";
const String apiPlansUrl = apiBaseUrl + "api/plans";
const String apiTagUrl = apiBaseUrl + "api/tags";
const String apiForgetUrl = apiBaseUrl + "api/forgot";
const String apiMessagesUrl = apiBaseUrl + "api/messages";
const String apiCheckoutUrl = apiBaseUrl + "api/checkout";
const String apiEmailVerify = apiBaseUrl + "api/email/verify";
const String apiSearchUrl = apiBaseUrl + "api/search";
